name: hgu_shop
description: hgu_shop_app

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_signin_button: ^0.2.5
#  google_sign_in: ^4.0.0
#  firebase_auth:
  firebase_auth: ^0.14.0
  google_sign_in: ^4.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

